CREATE TABLE BOOK_AUTHOR (
    BookID INT NOT NULL,
    AuthorID INT NOT NULL,
    PRIMARY KEY (BookID, AuthorID),
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID),
    FOREIGN KEY (AuthorID) REFERENCES AUTHOR(AuthorID)
);
